language: python
notifications:
  email: false
python:
  - "2.7"
services: mysql
env:
  - DJANGO=1.3.1
install:
  - pip install -q -r requirements.txt
  - pip install -q -r requirements_test.txt
before_script:
  - mysql -e 'create database networkapi;'
  - python manage.py syncdb --noinput
script:
  - python manage.py test
